name: Validate JSON

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate JSON files
        run: |
          sudo apt-get install -y jq
          find . -name "*.json" -print0 | xargs -0 -n1 jq empty
      - name: Check duplicated identifiers
        run: |
          DUPLICATES=$(grep -R "\"identifier\"" behavior_pack | sort | uniq -d)
          if [ ! -z "$DUPLICATES" ]; then
            echo "‚ùå Identifiers duplicados encontrados:"
            echo "$DUPLICATES"
            exit 1
          fi
